version: '2.3' #needs to be version 2 to allow specifying gateway, see https://docs.docker.com/compose/compose-file/#ipam
networks:
  customnetwork:
    driver: nat
    ipam:
      driver: default
      config:
        - 
          subnet: 172.18.0.0/16
          gateway: 172.18.0.1 #errors if this isn't specified, see riverar's comment here https://github.com/moby/moby/issues/34777
services:
  dockerdebug:
    networks:
      customnetwork:
        ipv4_address: 172.18.0.2
    build:
      context: .\DockerDebug
      dockerfile: Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      DOTNET_USE_POLLING_FILE_WATCHER: '1'
      NUGET_PACKAGES: C:\.nuget\packages
    image: dockerdebug:dev
    ports: #exposes ports to the host machine e.g. developer's computer
      - "80:80"
      - "4022:4022"
      - "3702:3702/udp"
    volumes:
      - .\DockerDebug:C:\app:rw
      - C:\Users\<USER>\onecoremsvsmon\15.0.26919.1:C:\remote_debugger:ro